//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class CollegeMSEntities : DbContext
{
    public CollegeMSEntities()
        : base("name=CollegeMSEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<AccountReceivable> AccountReceivables { get; set; }
    public virtual DbSet<AccountReceivableType> AccountReceivableTypes { get; set; }
    public virtual DbSet<AddressDetail> AddressDetails { get; set; }
    public virtual DbSet<AddressType> AddressTypes { get; set; }
    public virtual DbSet<Category> Categories { get; set; }
    public virtual DbSet<Cours> Courses { get; set; }
    public virtual DbSet<CourseSubject> CourseSubjects { get; set; }
    public virtual DbSet<Department> Departments { get; set; }
    public virtual DbSet<Designation> Designations { get; set; }
    public virtual DbSet<DocumentType> DocumentTypes { get; set; }
    public virtual DbSet<DocVarificationStatu> DocVarificationStatus { get; set; }
    public virtual DbSet<EducationDetail> EducationDetails { get; set; }
    public virtual DbSet<FeeStatu> FeeStatus { get; set; }
    public virtual DbSet<IlligibilityDocument> IlligibilityDocuments { get; set; }
    public virtual DbSet<IlligibilityExamination> IlligibilityExaminations { get; set; }
    public virtual DbSet<LedgerAccount> LedgerAccounts { get; set; }
    public virtual DbSet<LedgerAccountAppliedTo> LedgerAccountAppliedToes { get; set; }
    public virtual DbSet<MenuAndSubMenu> MenuAndSubMenus { get; set; }
    public virtual DbSet<MeritList> MeritLists { get; set; }
    public virtual DbSet<MessageType> MessageTypes { get; set; }
    public virtual DbSet<ModeOfPayment> ModeOfPayments { get; set; }
    public virtual DbSet<Organization> Organizations { get; set; }
    public virtual DbSet<ParentDetail> ParentDetails { get; set; }
    public virtual DbSet<PaymentTransaction> PaymentTransactions { get; set; }
    public virtual DbSet<Prospectus> Prospectus { get; set; }
    public virtual DbSet<Registration> Registrations { get; set; }
    public virtual DbSet<RegistrationStatu> RegistrationStatus { get; set; }
    public virtual DbSet<Relation> Relations { get; set; }
    public virtual DbSet<RequiredDocument> RequiredDocuments { get; set; }
    public virtual DbSet<ResultMaster> ResultMasters { get; set; }
    public virtual DbSet<StudentCours> StudentCourses { get; set; }
    public virtual DbSet<TransationType> TransationTypes { get; set; }
    public virtual DbSet<UserRight> UserRights { get; set; }
    public virtual DbSet<User> Users { get; set; }
    public virtual DbSet<UserStatu> UserStatus { get; set; }
    public virtual DbSet<UserType> UserTypes { get; set; }
    public virtual DbSet<Upload> Uploads { get; set; }
}
