//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class AccountReceivable
{
    public long ID { get; set; }
    public long LedgerAccountId { get; set; }
    public long AccountReceivableTypeId { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual AccountReceivableType AccountReceivableType { get; set; }
    public virtual LedgerAccount LedgerAccount { get; set; }
}

public partial class AccountReceivableType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AccountReceivableType()
    {
        this.AccountReceivables = new HashSet<AccountReceivable>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> CourseId { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AccountReceivable> AccountReceivables { get; set; }
}

public partial class AddressDetail
{
    public long ID { get; set; }
    public long UserId { get; set; }
    public long AddressTypeID { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Country { get; set; }
    public Nullable<int> Pincode { get; set; }
    public string Phone1 { get; set; }
    public string Phone2 { get; set; }
    public string Email1 { get; set; }
    public string Email2 { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual AddressType AddressType { get; set; }
    public virtual User User { get; set; }
}

public partial class AddressType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AddressType()
    {
        this.AddressDetails = new HashSet<AddressDetail>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AddressDetail> AddressDetails { get; set; }
}

public partial class Category
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Category()
    {
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class Cours
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cours()
    {
        this.CourseSubjects = new HashSet<CourseSubject>();
        this.MeritLists = new HashSet<MeritList>();
        this.Registrations = new HashSet<Registration>();
        this.StudentCourses = new HashSet<StudentCours>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public long ParentID { get; set; }
    public string Duration { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<CourseSubject> CourseSubjects { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<MeritList> MeritLists { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Registration> Registrations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StudentCours> StudentCourses { get; set; }
}

public partial class CourseSubject
{
    public long ID { get; set; }
    public long CourseId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Cours Cours { get; set; }
}

public partial class Department
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Department()
    {
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class Designation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Designation()
    {
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class DocumentType
{
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<bool> IsValid { get; set; }
}

public partial class DocVarificationStatu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public DocVarificationStatu()
    {
        this.Registrations = new HashSet<Registration>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Registration> Registrations { get; set; }
}

public partial class EducationDetail
{
    public long ID { get; set; }
    public long UserId { get; set; }
    public string BoardOrUniversity { get; set; }
    public string SchoolOrCallege { get; set; }
    public string YearOfpassing { get; set; }
    public Nullable<int> MarkObtained { get; set; }
    public Nullable<int> PercentageObtained { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual User User { get; set; }
}

public partial class FeeStatu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FeeStatu()
    {
        this.Registrations = new HashSet<Registration>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Registration> Registrations { get; set; }
}

public partial class IlligibilityDocument
{
    public int ID { get; set; }
    public Nullable<int> ExaminationID { get; set; }
    public Nullable<int> Year { get; set; }
    public string BoardUniversity { get; set; }
    public string NameOfInstitution { get; set; }
    public Nullable<int> TotalScore { get; set; }
    public Nullable<int> GainedScore { get; set; }
    public string Grade { get; set; }
    public Nullable<decimal> Percentage { get; set; }
    public string Subject { get; set; }
    public Nullable<int> RegistrationID { get; set; }
    public Nullable<bool> IsValidated { get; set; }
    public string ValidationRemarks { get; set; }
    public Nullable<bool> IsValid { get; set; }
    public string Remarks { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
    public Nullable<int> DocumentTypeID { get; set; }
    public string ContentType { get; set; }
    public string DocumentName { get; set; }
    public Nullable<int> UploadId { get; set; }
}

public partial class IlligibilityExamination
{
    public int ID { get; set; }
    public string Name { get; set; }
    public Nullable<bool> IsValid { get; set; }
}

public partial class LedgerAccount
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LedgerAccount()
    {
        this.AccountReceivables = new HashSet<AccountReceivable>();
        this.PaymentTransactions = new HashSet<PaymentTransaction>();
    }

    public long ID { get; set; }
    public long AppliedToID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AccountReceivable> AccountReceivables { get; set; }
    public virtual LedgerAccountAppliedTo LedgerAccountAppliedTo { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
}

public partial class LedgerAccountAppliedTo
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LedgerAccountAppliedTo()
    {
        this.LedgerAccounts = new HashSet<LedgerAccount>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<LedgerAccount> LedgerAccounts { get; set; }
}

public partial class MenuAndSubMenu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public MenuAndSubMenu()
    {
        this.UserRights = new HashSet<UserRight>();
    }

    public long ID { get; set; }
    public long ParentId { get; set; }
    public string LinkName { get; set; }
    public long PageAndControlId { get; set; }
    public string Type { get; set; }
    public string Descrition { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool IsValid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRight> UserRights { get; set; }
}

public partial class MeritList
{
    public long ID { get; set; }
    public string Name { get; set; }
    public long CourseId { get; set; }
    public decimal CutOffPercentile { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Cours Cours { get; set; }
}

public partial class MessageType
{
    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
}

public partial class ModeOfPayment
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ModeOfPayment()
    {
        this.PaymentTransactions = new HashSet<PaymentTransaction>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
}

public partial class Organization
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Organization()
    {
        this.Prospectus = new HashSet<Prospectus>();
        this.Registrations = new HashSet<Registration>();
        this.RequiredDocuments = new HashSet<RequiredDocument>();
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Address1 { get; set; }
    public string Address2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Postalcode { get; set; }
    public string Website { get; set; }
    public string Email1 { get; set; }
    public string Email2 { get; set; }
    public string Mobile1 { get; set; }
    public string Mobile2 { get; set; }
    public string Phone1 { get; set; }
    public string phone2 { get; set; }
    public string TIN { get; set; }
    public string RegNumber { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Prospectus> Prospectus { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Registration> Registrations { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<RequiredDocument> RequiredDocuments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class ParentDetail
{
    public long ID { get; set; }
    public long UserId { get; set; }
    public string Name { get; set; }
    public Nullable<long> RelationId { get; set; }
    public string Occupation { get; set; }
    public Nullable<decimal> AnualIncome { get; set; }
    public string ContactNumber { get; set; }
    public string Email { get; set; }
    public string PAN { get; set; }
    public string Adhar { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Relation Relation { get; set; }
    public virtual User User { get; set; }
}

public partial class PaymentTransaction
{
    public long ID { get; set; }
    public long UserId { get; set; }
    public Nullable<decimal> Amount { get; set; }
    public long TransationTypeId { get; set; }
    public long LedgerAccounId { get; set; }
    public long ModeOfPayment { get; set; }
    public string TransactionId { get; set; }
    public Nullable<System.DateTime> TransactionInitDate { get; set; }
    public Nullable<System.DateTime> CreditOrDebitDate { get; set; }
    public string FromAccountNumber { get; set; }
    public string ToAccountNumber { get; set; }
    public string FromBankDetails { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual LedgerAccount LedgerAccount { get; set; }
    public virtual ModeOfPayment ModeOfPayment1 { get; set; }
    public virtual TransationType TransationType { get; set; }
    public virtual User User { get; set; }
}

public partial class Prospectus
{
    public long ID { get; set; }
    public Nullable<long> RegistrationId { get; set; }
    public string Name { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Organization Organization { get; set; }
    public virtual Registration Registration { get; set; }
}

public partial class Registration
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Registration()
    {
        this.Prospectus = new HashSet<Prospectus>();
    }

    public long ID { get; set; }
    public Nullable<long> CourseId { get; set; }
    public string TotalFee { get; set; }
    public Nullable<long> FeeStatus { get; set; }
    public Nullable<long> RegistrationStatus { get; set; }
    public Nullable<long> DocVarificationStatus { get; set; }
    public Nullable<long> UserId { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }
    public string Cast { get; set; }
    public string Nationality { get; set; }
    public Nullable<System.DateTime> DateOfBirth { get; set; }
    public string MotherName { get; set; }
    public string MotherOccupation { get; set; }
    public Nullable<decimal> MotherIncome { get; set; }
    public string FatherName { get; set; }
    public string FatherOccupation { get; set; }
    public Nullable<decimal> FatherIncome { get; set; }
    public string AddressLine1 { get; set; }
    public string AddressLine2 { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string MobileNumber { get; set; }
    public Nullable<bool> IsMinority { get; set; }
    public Nullable<decimal> Duration_in_UP { get; set; }
    public Nullable<int> CategoryID { get; set; }
    public Nullable<int> Subject1 { get; set; }
    public Nullable<int> Subject2 { get; set; }
    public Nullable<int> Subject3 { get; set; }
    public Nullable<int> Subject4 { get; set; }
    public string BankName { get; set; }
    public string BankAccountNumber { get; set; }
    public string BankAddress { get; set; }
    public string BankIFSCCode { get; set; }
    public string RegistrationNumber { get; set; }
    public string AdmissionNumber { get; set; }
    public Nullable<bool> IsAdmissionGranted { get; set; }
    public string PhotoFileName { get; set; }
    public Nullable<int> UploadId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Pincode { get; set; }
    public string Email { get; set; }
    public string PhoneNumber { get; set; }
    public string MotherMobileNumber { get; set; }
    public string FatherMobileNumber { get; set; }
    public string Religion { get; set; }

    public virtual Cours Cours { get; set; }
    public virtual DocVarificationStatu DocVarificationStatu { get; set; }
    public virtual FeeStatu FeeStatu { get; set; }
    public virtual Organization Organization { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Prospectus> Prospectus { get; set; }
    public virtual RegistrationStatu RegistrationStatu { get; set; }
}

public partial class RegistrationStatu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public RegistrationStatu()
    {
        this.Registrations = new HashSet<Registration>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Registration> Registrations { get; set; }
}

public partial class Relation
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Relation()
    {
        this.ParentDetails = new HashSet<ParentDetail>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ParentDetail> ParentDetails { get; set; }
}

public partial class RequiredDocument
{
    public long ID { get; set; }
    public string Name { get; set; }
    public long CourseId { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Organization Organization { get; set; }
}

public partial class ResultMaster
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public ResultMaster()
    {
        this.StudentCourses = new HashSet<StudentCours>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StudentCours> StudentCourses { get; set; }
}

public partial class StudentCours
{
    public long ID { get; set; }
    public long UserId { get; set; }
    public Nullable<long> CourseId { get; set; }
    public Nullable<long> ResultMasterId { get; set; }
    public Nullable<decimal> MarkObtained { get; set; }
    public Nullable<decimal> TotalMarks { get; set; }
    public Nullable<decimal> Percentile { get; set; }
    public Nullable<System.DateTime> CourseSession { get; set; }
    public string AdmitCardNumber { get; set; }
    public string UniversityRegNo { get; set; }
    public Nullable<System.DateTime> ExamDate { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual Cours Cours { get; set; }
    public virtual ResultMaster ResultMaster { get; set; }
    public virtual User User { get; set; }
}

public partial class TransationType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TransationType()
    {
        this.PaymentTransactions = new HashSet<PaymentTransaction>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
}

public partial class Upload
{
    public int ID { get; set; }
    public Nullable<int> Type { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<int> CreatedBy { get; set; }
    public string Remarks { get; set; }
    public byte[] File { get; set; }
}

public partial class User
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {
        this.AddressDetails = new HashSet<AddressDetail>();
        this.EducationDetails = new HashSet<EducationDetail>();
        this.ParentDetails = new HashSet<ParentDetail>();
        this.PaymentTransactions = new HashSet<PaymentTransaction>();
        this.StudentCourses = new HashSet<StudentCours>();
        this.UserRights = new HashSet<UserRight>();
    }

    public long ID { get; set; }
    public string LoginId { get; set; }
    public string Password { get; set; }
    public long UserTypeId { get; set; }
    public long StatusId { get; set; }
    public Nullable<long> CategoryId { get; set; }
    public Nullable<long> DepartmentId { get; set; }
    public Nullable<long> DesignationId { get; set; }
    public string FName { get; set; }
    public string MName { get; set; }
    public string LName { get; set; }
    public string Email1 { get; set; }
    public string Email2 { get; set; }
    public string Mobile1 { get; set; }
    public string Mobile2 { get; set; }
    public Nullable<System.DateTime> DOB { get; set; }
    public string PAN { get; set; }
    public string AdharNumber { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<AddressDetail> AddressDetails { get; set; }
    public virtual Category Category { get; set; }
    public virtual Department Department { get; set; }
    public virtual Designation Designation { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<EducationDetail> EducationDetails { get; set; }
    public virtual Organization Organization { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<ParentDetail> ParentDetails { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<StudentCours> StudentCourses { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRight> UserRights { get; set; }
    public virtual UserStatu UserStatu { get; set; }
    public virtual UserType UserType { get; set; }
}

public partial class UserRight
{
    public long ID { get; set; }
    public long UserTypeId { get; set; }
    public long UserId { get; set; }
    public long MenuId { get; set; }
    public long MenuParentId { get; set; }
    public string Descrition { get; set; }
    public Nullable<bool> IsActive { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool IsValid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    public virtual MenuAndSubMenu MenuAndSubMenu { get; set; }
    public virtual User User { get; set; }
    public virtual UserType UserType { get; set; }
}

public partial class UserStatu
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserStatu()
    {
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}

public partial class UserType
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public UserType()
    {
        this.UserRights = new HashSet<UserRight>();
        this.Users = new HashSet<User>();
    }

    public long ID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public Nullable<long> OrgId { get; set; }
    public string Extra1 { get; set; }
    public string Extra2 { get; set; }
    public string Extra3 { get; set; }
    public string Remarks { get; set; }
    public bool Valid { get; set; }
    public Nullable<long> CreatedBy { get; set; }
    public Nullable<System.DateTime> CreatedDate { get; set; }
    public Nullable<long> ModifiedBy { get; set; }
    public Nullable<System.DateTime> ModifiedDate { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<UserRight> UserRights { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<User> Users { get; set; }
}
